version: '3.9'

services:
  elasticsearch-hot:
    image: elasticsearch:8.11.3
    container_name: elasticsearch-hot
    volumes:
      - ./elasticsearch/01/config/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw
      - ./elasticsearch/01/data:/usr/share/elasticsearch/data
    environment:
      discovery.seed_hosts: elasticsearch-hot,elasticsearch-warm
      cluster.initial_master_nodes: elastic-hot,elastic-warm
      node.roles: master,data_content,data_hot
      ELASTIC_USERNAME: "root"
      ELASTIC_PASSWORD: "P@ssw0rd"
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      - elasticsearch-warm

  elasticsearch-warm:
    image: elasticsearch:8.11.3
    container_name: elasticsearch-warm
    volumes:
      - ./elasticsearch/02/config/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw
      - ./elasticsearch/02/data:/usr/share/elasticsearch/data
    environment:
      discovery.seed_hosts: elasticsearch-hot,elasticsearch-warm
      cluster.initial_master_nodes: elastic-hot,elastic-warm
      node.roles: master,data_warm
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - elk

  logstash:
    image: logstash:8.11.3
    container_name: logstash
    volumes:
      - ./logstash/config.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch-hot

  kibana:
    image: kibana:8.11.3
    container_name: kibana
    depends_on:
      - elasticsearch-hot
    volumes:
      - ./kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - elk
    ports:
      - "5601:5601"

  filebeat:
    image: elastic/filebeat:8.11.4
    container_name: filebeat
    privileged: true
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/config.yml:/usr/share/filebeat/filebeat.yml:Z
      - /var/lib/docker:/var/lib/docker:Z
      - /var/run/docker.sock:/var/run/docker.sock:Z
    depends_on:
      - logstash
    networks:
      - elk

  application:
    image: library/python:3.9-alpine
    container_name: application
    volumes:
      - ./pinger/:/opt/:Z
    entrypoint: python3 /opt/run.py
    networks:
      - elk

networks:
  elk:
    driver: bridge
