server.name: kibana
server.host: 0.0.0.0
server.publicBaseUrl: "http://localhost:5601"
monitoring.ui.container.elasticsearch.enabled: true
elasticsearch.hosts: [ "http://elasticsearch-hot:9200" ]
elasticsearch.username: root
elasticsearch.password: P@ssw0rd
